version: '3.7'

services:
  highs-runner:
    image: openjdk:8
    working_dir: /opt/app
    environment:
      SPRING_PROFILES_ACTIVE: dev
    volumes:
      - ./highs-runner:/mnt/src:ro
      - ./bin:/mnt/bin:ro
      - ./docker/entrypoints:/entrypoints:ro
    entrypoint: /entrypoints/spring-boot-entrypoint.sh
    command: java -jar -Xmx256m  highs-runner.jar --server.port=8081 --spring.profiles.active=dev
    ports:
      - 8082:8082
    container_name: highs-runner
    tmpfs:
      - /tmp


